API_HOST_URL: 'https://campus.aulasneo.com'
ENVIRONMENT_DISPLAY_NAME: 'Campus Aulasneo'
PLATFORM_NAME: 'Campus Aulasneo'
PLATFORM_DESTINATION_NAME: 'Campus Aulasneo'
FEEDBACK_EMAIL_ADDRESS: 'support@aulasneo.com'
API_URL_VERSION:
  BLOCKS: 'v1'
ECOMMERCE_URL: 'https://ecommerce.campus.aulasneo.com'
COURSE_VIDEOS_ENABLED: true
COURSE_ENROLLMENT :
  TYPE : 'native'
DISCOVERY:
  TYPE: 'native'
PROGRAM:
  ENABLED: false
DISCUSSIONS_ENABLED: true
COURSE_DATES_ENABLED: true
YOUTUBE_PLAYER:
  ENABLED: true
  API_KEY: 'AIzaSyCf2-a7NZ5OTs7DxzR4qlb2dEjzd42opgM'
CERTIFICATES_ENABLED: true
COURSE_SHARING_ENABLED: true
USING_VIDEO_PIPELINE: false
USER_PROFILES_ENABLED: true
BADGES_ENABLED: true
REGISTRATION_ENABLED: true
APP_REVIEWS_ENABLED: true
DOWNLOAD_TO_SD_CARD_ENABLED: true
ANNOUNCEMENTS_ENABLED: true
